FROM node:20-slim

ARG repo

# build-essential: compilers etc.
# devscripts: make command etc.
# java jdk: android sdk tools require it
RUN apt update -y

RUN apt -y install git curl unzip
RUN apt -y install npm
# version set from https://docs.gradle.org/current/userguide/compatibility.html
RUN apt -y install default-jdk

# install android sdk
# download URL: https://developer.android.com/studio#command-tools
ENV ANDROID_HOME=/root
ENV PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools
RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -o sdktools.zip && \
    unzip sdktools.zip -d /root && \
    rm sdktools.zip
RUN mkdir ~/.android && touch ~/.android/repositories.cfg && \
    yes | /root/cmdline-tools/bin/sdkmanager --sdk_root=/root/cmdline-tools/ "platform-tools" "build-tools;36.1.0" "platforms;andr>

# install android ndk
# 'ndk-bundle' is the default directory name when NDK is installed through Android Studio so reusing that naming convention
# download URL: https://developer.android.com/ndk/downloads
RUN curl -L https://dl.google.com/android/repository/android-ndk-r29-linux.zip?hl=fr -o androidndk.zip && \
    unzip androidndk.zip -d /root && \
    rm androidndk.zip && \
    mv /root/android-ndk* /root/ndk-bundle

RUN yes | /root/cmdline-tools/bin/sdkmanager --licenses --sdk_root=/root/cmdline-tools/

# setup env vars and paths
ENV CONTAINER=true \
    ANDROID_SDK_PATH=/root \
    ANDROID_SDK_ROOT=/root \
    ANDROID_NDK_PATH=/root/ndk-bundle \
    ANDROID_NDK_ROOT=/root/ndk-bundle

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"

# RUN npm i -g npm eas-cli

WORKDIR /root/build

RUN apt -y install jq sudo bash

COPY entrypoint.sh /docker-entrypoint.d/

RUN chmod +x /docker-entrypoint.d/entrypoint.sh
CMD ["sh", "/docker-entrypoint.d/entrypoint.sh"]
